#### 2023-05-02

#### 1교시

In [ ]:
# lr.interception_ 의 뜻은?
y 절편

In [ ]:
# 선형회귀 분석의 기본 가정 
두 변수의 관계는 ( 선형 )이다 -> 선형성
오차항의 확률분포는 ( 정규분포 )를 이룬다 -> 오차의 정규성
오차항의 평균은 ( 0 )이다
오차항들끼리는 ( 독립 )이다

In [ ]:
# cars 속도가 70, 90, 100일 때의 제동거리를 신뢰도 99%로 예측하는 코드로 작성하시오.
fit_cars = lm(dist ~ speed,data = cars)
new = data.frame(speed = c(70,90,100))
predict(fit_cars,new, interval = 'confidence', level = 0.99) 

In [2]:
import pandas as pd
cars = pd.read_csv("./Documents/cars.csv")[['speed','dist']]
cars

FileNotFoundError: [Errno 2] No such file or directory: './Documents/cars.csv'

In [ ]:
# 결정계수란?
R^2 모형의 설명력 SSR/SST = 1 - SSE/SST
Adjusted R squard

In [ ]:
선형분석은 기본적으로 ( 상관 )관계를 규명하는 것이다.
'원인'으로 간주되는 변수 X를 ( 설명변수 ), 종속변수 y를 ( 반응변수 )라고 부른다.

In [ ]:
선형회귀의 평가지표 metrics는?
MAE ( Mean Absolute Error )
MSE ( Mean Squared Error )
RMSE ( Root Mean Squared Error )
R^2

In [ ]:
OLS : ordinary least squares

In [ ]:
# 상관분석은 인과관계를 가정한다. yes or no
no

In [ ]:
IQR을 이용해 이상치 데이터를 검출하는 방식
(1/4*100)-1.5*IQR 
(3/4*100)+1.5*IQR 

In [ ]:
여러 알고리즘을 사용하여 예측 결과를 만들고 그 예측 결과들을 모아 다시 학습하여
최종 예측 결과물을 도출하는 앙상블 기법은?
스태킹

In [ ]:
SMOTE 기법: 최근접 이웃[k-NN 알고리즘] 알고리즘을 활용하여 오버샘플링하는 방법 

In [ ]:
MSE에 루트를 씌운 것( RMSE )
실제값과 예측값의 차이를 절대값을 변환해 평균한 것( MAE )
실제값의 분산 대비 예측값의 분산 비율을 지표로 하며, 1에 가까울 수록 예측 정확도가 높다( R^2 )
실제값과 예측값의 차이를 제곱해 평균한 것( MSE )

##### 2교시

In [ ]:
다중 선형회귀 분석 관련 PDF로 수업 진행

##### 3교시

In [5]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

In [22]:
X = np.arange(4)[:, np.newaxis]
poly = PolynomialFeatures(degree=2)
poly_ftr = poly.fit_transform(X)
poly_ftr

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.],
       [1., 3., 9.]])

In [33]:
def ploynomoial_func(X):
    y = 1+2*X+3*X*2+4*X**3
    return y

In [34]:
y = ploynomoial_func(X)

In [35]:
from sklearn.linear_model import LinearRegression

In [36]:
model = LinearRegression()
model.fit(poly_ftr,y)

LinearRegression()

In [37]:
model.coef_

array([[  0. , -10.8,  18. ]])

In [39]:
X = np.arange(4).reshape(2,2)
X

array([[0, 1],
       [2, 3]])

In [40]:
poly = PolynomialFeatures(degree=3)
poly_ftr = poly.fit_transform(X)
poly_ftr

array([[ 1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.,  8., 12., 18., 27.]])

In [42]:
def ploynomoial_func(X):
    y = 1+2*X[:,0]+3*X[:,0]*2+4*X[:,1]**3
    return y

In [43]:
y = ploynomoial_func(X)
y

array([  5, 125])

In [44]:
model = LinearRegression()
model.fit(poly_ftr, y)

LinearRegression()

In [45]:
model.coef_

array([0.        , 0.18018018, 0.18018018, 0.36036036, 0.54054054,
       0.72072072, 0.72072072, 1.08108108, 1.62162162, 2.34234234])

##### 4교시

##### 5교시

##### 6교시

In [46]:
import pandas as pd
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data"
names = ["CRIM", "ZN", "INDUS", "CHAS", "NOX", "RM", "AGE", "DIS", "RAD", "TAX", "PTRATIO", "B", "LSTAT", "MEDV"]
data = pd.read_csv(url, delim_whitespace=True, names=names)
data 

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [47]:
X_data = data.iloc[:, :-1]
y_target = data.iloc[:,-1]
y_target[:3]

0    24.0
1    21.6
2    34.7
Name: MEDV, dtype: float64

In [50]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import cross_val_score

In [53]:
ridge = Ridge()
MSE = cross_val_score(ridge, X_data, y_target, scoring='neg_mean_squared_error',cv=5)

In [54]:
RMSE = np.sqrt(np.mean(-MSE))
RMSE

5.938579888954655

In [61]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [62]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y_target, test_size=0.25, random_state=42)
ridge = Ridge()
ridge.fit(X_train, y_train)
y_pred = ridge.predict(X_test)
mse = mean_squared_error(y_test, y_pred) 
mse

22.480475501233865

In [63]:
# alpha = [0.1,0.5,1,2,5,10] 에 대한 mean_squared_error 6개를 구해 봅시다.

In [65]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y_target, test_size = 0.25)
alphas=[0.1, 0.5, 1,2,5,10]
for i in alphas:
    ridge=Ridge(alpha=i)
    
ridge.fit(X_train,y_train)
pred=ridge.predict(X_test)
mean_squared_error(y_test,pred) 

21.631829287701912

In [66]:
from sklearn.linear_model import Lasso

In [68]:
alphas=[0.1, 0.5, 1,2,5,10]
for i in alphas:
    lasso=Lasso(alpha=i)
    lasso.fit(X_train,y_train)
    pred=lasso.predict(X_test)
    mse = mean_squared_error(y_test,pred) 
    print(mse)

21.63431895864836
21.57938256228063
22.78456923233173
25.550735653311587
28.568609159111006
28.947480477721342


In [69]:
from sklearn.linear_model import ElasticNet

In [70]:
alphas=[0.1, 0.5, 1,2,5,10]
for i in alphas:
    elastic=ElasticNet(alpha=i)
    elastic.fit(X_train,y_train)
    pred=elastic.predict(X_test)
    mse = mean_squared_error(y_test,pred) 
    print(mse)

21.72650657579705
22.21483855931721
22.848745083115926
23.95060194979052
26.438203410466148
28.16479210390878
